#!/usr/bin/env python3
"""Render two PRD files from collected interview answers.

Input: a JSON document (file or stdin) with four top-level keys matching
the four dimensions in ``SKILL.md``. Each key's value is an object whose
fields are rendered as a bullet list under the section.

Outputs:
  * ``--out``           — full PRD (``PRD.md``), eval-agent visible.
  * ``--out-improver``  — redacted PRD (``PRD.improver_only.md``),
                          improver-agent visible. Section 4
                          (Evaluation) is dropped entirely. In section
                          3 (Output format), the
                          ``automatic_validation_rule`` field — which
                          would tell the improver exactly how its
                          outputs are checked — is also dropped.
  * ``--out-choices``   — interview transcript (``PRD.choice.md``),
                          recording every AskUserQuestion round and the
                          user's answer.

Optional wiki outputs:
  * ``--eval-wiki-dir``  — checked-out wiki repo for ``<skill>-eval``.
                          Writes full ``PRD.md`` and ``PRD-Choices.md``.
  * ``--skill-wiki-dir`` — checked-out wiki repo for ``<skill>``. Writes
                          redacted/training-visible ``PRD.md`` only.

Either ``--out`` or ``--out-improver`` may be ``-`` (stdout), but they
cannot both be stdout.

Convenience: pass ``--out-dir <DIR>`` to write all standard files inside
that directory (``<DIR>/PRD.md``, ``<DIR>/PRD.improver_only.md``, and
``<DIR>/PRD.choice.md``); ``--out`` / ``--out-improver`` /
``--out-choices`` then become optional overrides.

Zero external dependencies.
"""
from __future__ import annotations

import argparse
import datetime as _dt
import json
import sys
from copy import deepcopy
from pathlib import Path
from typing import Any


_REQUIRED_SECTIONS = ("environment", "goal", "output_format", "evaluation")

_SECTION_HEADINGS = {
    "environment": "1. Environment",
    "goal": "2. Goal",
    "output_format": "3. Output format",
    "evaluation": "4. Evaluation",
}

# Field names that MUST be stripped from the improver-visible PRD.
# Keep this list extremely conservative — adding a leaky field name
# here is much cheaper than discovering Goodhart in an iter loop.
_IMPROVER_REDACTED_FIELDS = {
    "output_format": {
        "automatic_validation_rule",
        "validation_rule",
        "validator",
        "validator_command",
    },
}


def _render_section(title: str, payload: Any) -> str:
    """Render a single PRD section.

    ``payload`` can be a string (dumped verbatim), a dict (key→value
    bullets), or a list (plain bullets). Anything else is coerced via
    str.
    """
    out = [f"## {title}", ""]
    if isinstance(payload, str):
        out.append(payload.rstrip())
    elif isinstance(payload, dict):
        if not payload:
            out.append("_(no content — section is empty, this PRD is incomplete)_")
        else:
            for key, val in payload.items():
                pretty_key = key.replace("_", " ")
                if isinstance(val, list):
                    joined = ", ".join(str(v) for v in val) if val else "_(none)_"
                    out.append(f"- **{pretty_key}**: {joined}")
                elif isinstance(val, dict):
                    out.append(f"- **{pretty_key}**:")
                    for k2, v2 in val.items():
                        out.append(f"    - {k2}: {v2}")
                else:
                    out.append(f"- **{pretty_key}**: {val}")
    elif isinstance(payload, list):
        if not payload:
            out.append("_(no content — section is empty, this PRD is incomplete)_")
        for item in payload:
            out.append(f"- {item}")
    else:
        out.append(str(payload))
    out.append("")
    return "\n".join(out)


def _header(skill_name: str, *, improver_only: bool) -> list[str]:
    today = _dt.date.today().isoformat()
    if improver_only:
        banner = (
            f"> Generated by skillhone-prd on {today}. **Improver-visible** "
            f"copy. Section 4 (Evaluation) and any auto-validation rules "
            f"have been redacted to prevent the improver from overfitting "
            f"to its own grading rubric."
        )
        title = f"# PRD (improver view) — {skill_name}"
    else:
        banner = (
            f"> Generated by skillhone-prd on {today}. **Eval-visible** copy. "
            f"This file lives in `{skill_name}-eval` (orchestrator-only). "
            f"It must **never** be copied into the skill repo."
        )
        title = f"# PRD — {skill_name}"
    return [title, "", banner, "", ""]


def _choices_header(skill_name: str) -> list[str]:
    today = _dt.date.today().isoformat()
    return [
        f"# PRD choices — {skill_name}",
        "",
        (
            f"> Generated by skillhone-prd on {today}. Records the "
            f"AskUserQuestion choices that produced `PRD.md`. Keep this "
            f"file in the eval repo with the PRD artifacts."
        ),
        "",
        "",
    ]


def _redact_for_improver(data: dict[str, Any]) -> dict[str, Any]:
    """Return a deep-copied ``data`` with eval-leakage fields stripped.

    Specifically: drop section 4 entirely, and strip
    ``_IMPROVER_REDACTED_FIELDS`` from any other section.
    """
    redacted = deepcopy(data)
    redacted.pop("evaluation", None)
    for section, banned in _IMPROVER_REDACTED_FIELDS.items():
        payload = redacted.get(section)
        if isinstance(payload, dict):
            for key in list(payload.keys()):
                if key in banned:
                    payload.pop(key, None)
    return redacted


def render(
    skill_name: str,
    data: dict[str, Any],
    *,
    improver_only: bool = False,
) -> str:
    """Render the PRD as Markdown.

    When ``improver_only`` is True, section 4 is dropped and validation
    rules in section 3 are stripped.
    """
    payload = _redact_for_improver(data) if improver_only else data
    sections_to_render = [
        k for k in _REQUIRED_SECTIONS
        if not (improver_only and k == "evaluation")
    ]
    body = []
    for key in sections_to_render:
        title = _SECTION_HEADINGS[key]
        body.append(_render_section(title, payload.get(key, {})))
    return "\n".join(_header(skill_name, improver_only=improver_only)) + "\n".join(body)


def _answer_text(answer: Any) -> str:
    if isinstance(answer, list):
        return ", ".join(str(x) for x in answer)
    return str(answer)


def _render_choice_question(question: dict[str, Any], answer: Any) -> list[str]:
    header = question.get("header")
    title = question.get("question", "_(missing question text)_")
    prefix = f"**{header}** — " if header else ""
    out = [f"- {prefix}{title}"]
    options = question.get("options")
    if isinstance(options, list) and options:
        out.append("  - Options:")
        for option in options:
            if isinstance(option, dict):
                label = option.get("label", "")
                desc = option.get("description", "")
                suffix = f" — {desc}" if desc else ""
                out.append(f"    - `{label}`{suffix}")
            else:
                out.append(f"    - `{option}`")
    out.append(f"  - Answer: **{_answer_text(answer)}**")
    return out


def render_choices(skill_name: str, data: dict[str, Any]) -> str:
    """Render the AskUserQuestion transcript as ``PRD.choice.md``.

    Expected input shape:

    ``choices`` (or ``choice_log``) is a list of rounds. Each round should
    include ``questions`` exactly as passed to AskUserQuestion and
    ``answers`` as returned by the tool (question text → selected label or
    free-text answer). Extra fields such as ``dimension`` or ``notes`` are
    rendered when present.
    """
    choices = data.get("choices", data.get("choice_log", []))
    out = _choices_header(skill_name)
    if not choices:
        out.append("_(no AskUserQuestion rounds were recorded)_")
        out.append("")
        return "\n".join(out)

    for idx, round_data in enumerate(choices, start=1):
        if not isinstance(round_data, dict):
            out.extend([f"## Round {idx}", "", f"- {round_data}", ""])
            continue
        title_bits = [f"Round {round_data.get('round', idx)}"]
        dimension = round_data.get("dimension")
        if dimension:
            title_bits.append(str(dimension))
        out.extend([f"## {' — '.join(title_bits)}", ""])
        if round_data.get("why"):
            out.append(f"- Why asked: {round_data['why']}")
        questions = round_data.get("questions", [])
        answers = round_data.get("answers", {})
        if isinstance(questions, list):
            for question in questions:
                if not isinstance(question, dict):
                    out.append(f"- {question}")
                    continue
                q_text = question.get("question", "")
                answer = answers.get(q_text, "_(no answer recorded)_") if isinstance(answers, dict) else answers
                out.extend(_render_choice_question(question, answer))
        if round_data.get("notes"):
            out.append(f"- Notes: {round_data['notes']}")
        out.append("")
    return "\n".join(out)


def _read_data(path: str | None) -> dict[str, Any]:
    if path is None or path == "-":
        raw = sys.stdin.read()
    else:
        raw = Path(path).read_text(encoding="utf-8")
    if not raw.strip():
        print("error: input JSON is empty", file=sys.stderr)
        sys.exit(2)
    try:
        data = json.loads(raw)
    except json.JSONDecodeError as e:
        print(f"error: invalid JSON — {e}", file=sys.stderr)
        sys.exit(2)
    if not isinstance(data, dict):
        print("error: top-level JSON must be an object", file=sys.stderr)
        sys.exit(2)
    missing = [k for k in _REQUIRED_SECTIONS if k not in data]
    if missing:
        print(f"warning: missing keys in input: {missing}", file=sys.stderr)
    return data


def _write_output(text: str, target: str) -> None:
    if target == "-":
        sys.stdout.write(text)
        return
    out_path = Path(target)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(text, encoding="utf-8")
    print(f"wrote {out_path}", file=sys.stderr)


def _write_wiki_pages(
    *,
    eval_wiki_dir: str | None,
    skill_wiki_dir: str | None,
    full_text: str,
    improver_text: str,
    choices_text: str,
) -> None:
    if eval_wiki_dir:
        eval_dir = Path(eval_wiki_dir)
        eval_dir.mkdir(parents=True, exist_ok=True)
        _write_output(full_text, str(eval_dir / "PRD.md"))
        _write_output(choices_text, str(eval_dir / "PRD-Choices.md"))
    if skill_wiki_dir:
        skill_dir = Path(skill_wiki_dir)
        skill_dir.mkdir(parents=True, exist_ok=True)
        _write_output(improver_text, str(skill_dir / "PRD.md"))


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--skill-name", required=True,
                    help="name of the skill the PRD is for (no -eval suffix)")
    ap.add_argument("--data", default="-",
                    help="path to JSON answers; '-' means stdin (default)")
    ap.add_argument("--out", default=None,
                    help="path to write full eval-visible PRD.md; '-' is stdout")
    ap.add_argument("--out-improver", default=None,
                    help="path to write redacted improver PRD.improver_only.md; '-' is stdout")
    ap.add_argument("--out-choices", default=None,
                    help="path to write AskUserQuestion transcript PRD.choice.md; '-' is stdout")
    ap.add_argument("--out-dir", default=None,
                    help=("write standard files to <DIR>/PRD.md, "
                          "<DIR>/PRD.improver_only.md, and <DIR>/PRD.choice.md; "
                          "--out / --out-improver / --out-choices still "
                          "override individual paths"))
    ap.add_argument("--eval-wiki-dir", default=None,
                    help=("checked-out Forgejo wiki repo for <skill>-eval; "
                          "writes full PRD.md and PRD-Choices.md"))
    ap.add_argument("--skill-wiki-dir", default=None,
                    help=("checked-out Forgejo wiki repo for <skill>; "
                          "writes redacted/training-visible PRD.md only"))
    args = ap.parse_args(argv)

    if args.out_dir is None and (
        args.out is None or args.out_improver is None or args.out_choices is None
    ):
        ap.error(
            "must provide either --out-dir, or --out, --out-improver, and --out-choices"
        )

    out_full = args.out
    out_improver = args.out_improver
    out_choices = args.out_choices
    if args.out_dir is not None:
        d = Path(args.out_dir)
        if out_full is None:
            out_full = str(d / "PRD.md")
        if out_improver is None:
            out_improver = str(d / "PRD.improver_only.md")
        if out_choices is None:
            out_choices = str(d / "PRD.choice.md")

    stdout_targets = [p for p in (out_full, out_improver, out_choices) if p == "-"]
    if len(stdout_targets) > 1:
        print(
            "error: cannot write multiple outputs to stdout at once; pick at most one",
            file=sys.stderr,
        )
        return 2

    data = _read_data(args.data)

    full_text = render(args.skill_name, data, improver_only=False)
    improver_text = render(args.skill_name, data, improver_only=True)
    choices_text = render_choices(args.skill_name, data)

    _write_output(full_text, out_full)
    _write_output(improver_text, out_improver)
    if out_choices is not None:
        _write_output(choices_text, out_choices)
    _write_wiki_pages(
        eval_wiki_dir=args.eval_wiki_dir,
        skill_wiki_dir=args.skill_wiki_dir,
        full_text=full_text,
        improver_text=improver_text,
        choices_text=choices_text,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
