// @ts-nocheck
const messages={
  en:{repositories:'Repositories',skillRepositories:'Skill repositories',code:'Code',skills:'Skills',issues:'Issues',pullRequests:'Pull requests',wiki:'Wiki',local:'Local',nothingHere:'Nothing here yet.',filter:'Filter',localRepos:'{count} local Skill repositories',updated:'Updated {time}',listSkills:'Repositories',listIssues:'Issues',listPrs:'Pull requests',listWiki:'Wiki',open:'Open',closed:'Closed',merged:'Merged',failed:'Failed',running:'Running',completed:'Completed',issue:'Issue',pr:'Pull request',wikiPage:'Wiki',repairs:'Repairs',imported:'Imported from {source} · default branch {branch}',sourceExisting:'existing Git repository',sourcePath:'local directory',sourceCodex:'Codex',sourceClaude:'Claude Code',commands:'Agent commands',opened:'Opened on {date}',updatedAt:'Updated {time}',evidence:'Issue evidence',noDescription:'No description.',trajectory:'Optimization runs',noRuns:'No optimization run recorded.',branch:'Branch: {branch}',linkedPrs:'Linked pull requests',noPr:'No repair pull request yet.',closesIssue:'Closes issue',changeSummary:'Change summary',noDiff:'No diff summary.',changedFiles:'Files changed',noFiles:'No changed files.',commits:'Commits',noCommits:'No commits.',workRecord:'Work record',noNotes:'No notes yet.',agentCommand:'Agent command',notFinished:'Not finished',issuesShort:'issues',prsShort:'pull requests',wikiShort:'wiki',runsShort:'repairs',allRepositories:'All repositories',backTo:'Back to {view}',openCount:'{count} Open',closedCount:'{count} Closed',mergedCount:'{count} Merged',searchPlaceholder:'Filter {view}',conversation:'Conversation',checks:'Checks',filesChanged:'Files changed'},
  zh:{repositories:'Repositories',skillRepositories:'Skill 仓库',code:'Code',skills:'Skills',issues:'Issues',pullRequests:'Pull Requests',wiki:'Wiki',local:'本地',nothingHere:'暂无记录。',filter:'筛选',localRepos:'{count} 个本地 Skill 仓库',updated:'更新于 {time}',listSkills:'Repositories',listIssues:'Issues',listPrs:'Pull Requests',listWiki:'Wiki',open:'开启',closed:'已关闭',merged:'已合并',failed:'失败',running:'运行中',completed:'已完成',issue:'Issue',pr:'Pull Request',wikiPage:'Wiki',repairs:'修复',imported:'导入自 {source} · 默认分支 {branch}',sourceExisting:'已有 Git 仓库',sourcePath:'本地目录',sourceCodex:'Codex',sourceClaude:'Claude Code',commands:'Agent 命令',opened:'创建于 {date}',updatedAt:'更新于 {time}',evidence:'Issue 证据',noDescription:'没有描述。',trajectory:'优化运行',noRuns:'尚无优化运行。',branch:'分支：{branch}',linkedPrs:'关联 Pull Requests',noPr:'尚无修复 Pull Request。',closesIssue:'关闭的 Issue',changeSummary:'变更摘要',noDiff:'暂无变更摘要。',changedFiles:'变更文件',noFiles:'没有变更文件。',commits:'提交',noCommits:'没有提交。',workRecord:'工作记录',noNotes:'暂无记录。',agentCommand:'Agent 命令',notFinished:'未结束',issuesShort:'Issues',prsShort:'Pull Requests',wikiShort:'Wiki',runsShort:'修复',allRepositories:'全部仓库',backTo:'返回{view}',openCount:'{count} 个开启',closedCount:'{count} 个已关闭',mergedCount:'{count} 个已合并',searchPlaceholder:'筛选{view}',conversation:'会话',checks:'检查',filesChanged:'变更文件'}
};
Object.assign(messages.en,{status:'Status',openIssues:'Open issues',openPrs:'Open pull requests',wikiPages:'Wiki pages',harnessStatus:'DeepSeek Harness',idle:'Idle',unavailable:'Unavailable',activeRuns:'{count} active runs',latestOnDemand:'tested release · official NPM · on demand',runnerUnavailable:'optional optimizer is not installed',recentRuns:'Recent optimization runs',activity:'Optimization activity',today:'Today',thisWeek:'This week',runsLabel:'runs',toolCalls:'Tool calls',notRecorded:'Not recorded',duration:'Duration',seconds:'{count}s',noRecentRuns:'No optimization runs recorded.',viewAll:'View all',lastSevenDays:'Last 7 days'});
Object.assign(messages.zh,{status:'Status',openIssues:'开启的 Issues',openPrs:'开启的 Pull Requests',wikiPages:'Wiki 页面',harnessStatus:'DeepSeek Harness',idle:'空闲',unavailable:'不可用',activeRuns:'{count} 个运行中任务',latestOnDemand:'已测试版本 · 官方 NPM · 按需安装',runnerUnavailable:'尚未安装可选优化器',recentRuns:'最近优化运行',activity:'优化活动',today:'今天',thisWeek:'本周',runsLabel:'次运行',toolCalls:'工具调用',notRecorded:'尚未记录',duration:'耗时',seconds:'{count}s',noRecentRuns:'尚无优化运行。',viewAll:'查看全部',lastSevenDays:'最近 7 天'});
Object.assign(messages.en,{triggerPolicy:'Repair and merge policy',immediate:'Immediate',scheduled:'Scheduled',everyMinutes:'Every {count} min',queued:'Queued',optimizing:'Optimizing',review:'In review',done:'Done',pipeline:'Optimization progress',managedHarness:'v{version} · managed by SkillHone',modelReady:'default model selected',modelMissing:'configure a model in Harness',policyCommand:'Trigger: {trigger} · Merge: {merge}',mergeReview:'approval inbox',mergeAutomatic:'automatic after tests'});
Object.assign(messages.zh,{triggerPolicy:'修复与合并策略',immediate:'Issue 后立即优化',scheduled:'定时优化',everyMinutes:'每 {count} 分钟',queued:'待处理',optimizing:'优化中',review:'待审阅',done:'已完成',pipeline:'优化进度',managedHarness:'v{version} · SkillHone 管理',modelReady:'已选择默认模型',modelMissing:'请在 Harness 中配置模型',policyCommand:'触发：{trigger} · 合并：{merge}',mergeReview:'进入审批收件箱',mergeAutomatic:'测试通过后自动合并'});
Object.assign(messages.en,{auditVerified:'host audit verified',auditFailed:'audit integrity failed'});
Object.assign(messages.zh,{auditVerified:'宿主审计已验证',auditFailed:'审计完整性异常'});
Object.assign(messages.en,{reproductionTests:'Reproduction tests',noTests:'No Issue-linked reproduction tests.',pending:'Pending',passing:'Passing'});
Object.assign(messages.zh,{reproductionTests:'复现测试',noTests:'这个 Issue 尚未关联复现测试。',pending:'待运行',passing:'通过'});
Object.assign(messages.en,{noRepositoryDocument:'This Skill repository has no README.md or SKILL.md.',documentTooLarge:'This document is too large to preview.'});
Object.assign(messages.zh,{noRepositoryDocument:'这个 Skill 仓库没有 README.md 或 SKILL.md。',documentTooLarge:'文档过大，无法预览。'});
Object.assign(messages.en,{approvalInbox:'Approval inbox',awaitingApproval:'Awaiting your approval',decisionRequired:'Your decision is required',noApprovals:'No pull requests need approval.',mergeApproval:'Merge approval required',mergeApprovalBody:'SkillHone will not merge this pull request on its own. Review the Issue, checks, commits, and files before deciding.',reviewAndMerge:'Review and merge',confirmMergeTitle:'Confirm local merge',confirmMergeBody:'This creates a merge commit on the local default branch and closes the linked Issue. Nothing is pushed.',cancel:'Cancel',mergeLocally:'Merge locally',mergedWithApproval:'Merged locally',localOnly:'Local only · never pushed',mergeFailed:'The pull request could not be merged.'});
Object.assign(messages.zh,{approvalInbox:'审批收件箱',awaitingApproval:'待你审批',decisionRequired:'需要你决定是否合并',noApprovals:'当前没有需要审批的 Pull Request。',mergeApproval:'需要合并审批',mergeApprovalBody:'SkillHone 不会自行合并这个 Pull Request。请先查看 Issue、检查结果、提交和文件，再作决定。',reviewAndMerge:'审阅并合并',confirmMergeTitle:'确认本地合并',confirmMergeBody:'这会在本地默认分支创建合并提交，并关闭关联 Issue；不会执行任何 push。',cancel:'取消',mergeLocally:'确认本地合并',mergedWithApproval:'已在本地合并',localOnly:'仅限本地 · 从不推送',mergeFailed:'Pull Request 合并失败。'});
Object.assign(messages.en,{mergeAndSyncBody:'This merges the local pull request, closes its Issue, and copies the result to the Agent runtime after creating a backup. Nothing is pushed.',mergeAndSync:'Merge and sync',syncRequired:'Merged · sync required',syncRequiredBody:'This Skill was imported in copy mode. Its Agent runtime still uses the previous version.',syncNow:'Sync to Agent',syncComplete:'Synced to Agent',syncCompleteBody:'The Agent runtime uses the merged Skill.',takeoverComplete:'Merged and active',takeoverCompleteBody:'This runtime points directly to the SkillHone repository, so no copy-back is needed.',syncBlocked:'Merged · sync blocked',syncBlockedBody:'SkillHone did not overwrite the Agent runtime because its copy-back safety check did not pass.',confirmSyncTitle:'Sync merged Skill',confirmSyncBody:'This copies the merged Skill to its Agent runtime directory and creates a backup first.',syncFailed:'The merged Skill could not be synchronized.'});
Object.assign(messages.zh,{mergeAndSyncBody:'这会合并本地 Pull Request、关闭关联 Issue，并在创建备份后把结果同步到 Agent 的 Skill 目录；不会执行任何 push。',mergeAndSync:'合并并同步',syncRequired:'已合并 · 等待同步',syncRequiredBody:'这个 Skill 使用 Copy 模式导入，Agent 当前仍在使用旧版本。',syncNow:'同步到 Agent',syncComplete:'已同步到 Agent',syncCompleteBody:'Agent 当前使用的已经是合并后的 Skill。',takeoverComplete:'已合并并生效',takeoverCompleteBody:'运行时直接指向 SkillHone 仓库，不需要复制回去。',syncBlocked:'已合并 · 同步受阻',syncBlockedBody:'Copy-back 安全检查未通过，SkillHone 没有覆盖 Agent 当前使用的版本。',confirmSyncTitle:'同步已合并的 Skill',confirmSyncBody:'这会先创建备份，再把合并后的 Skill 复制到 Agent 的运行时目录。',syncFailed:'已合并的 Skill 无法同步。'});
Object.assign(messages.en,{prDescription:'Pull request description',noPrDescription:'No review description was recorded.'});
Object.assign(messages.zh,{prDescription:'Pull Request 说明',noPrDescription:'这个 Pull Request 没有审阅说明。'});
Object.assign(messages.en,{evaluationGates:'Frozen evaluation gates',baseline:'Baseline',candidate:'Candidate',notEvaluated:'Not evaluated',failing:'Failing'});
Object.assign(messages.zh,{evaluationGates:'冻结评估门槛',baseline:'基线',candidate:'候选',notEvaluated:'尚未评估',failing:'未通过'});

// SVG path data from Primer Octicons. See THIRD_PARTY_NOTICES.md.
const iconPaths={
  issue:'<path d="M8 9.5a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3Z"/><path d="M8 0a8 8 0 1 1 0 16A8 8 0 0 1 8 0ZM1.5 8a6.5 6.5 0 1 0 13 0 6.5 6.5 0 0 0-13 0Z"/>',
  issueClosed:'<path d="M11.28 6.78a.75.75 0 0 0-1.06-1.06L7.25 8.69 5.78 7.22a.75.75 0 0 0-1.06 1.06l2 2a.75.75 0 0 0 1.06 0l3.5-3.5Z"/><path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0Zm-1.5 0a6.5 6.5 0 1 0-13 0 6.5 6.5 0 0 0 13 0Z"/>',
  pr:'<path d="M1.5 3.25a2.25 2.25 0 1 1 3 2.122v5.256a2.251 2.251 0 1 1-1.5 0V5.372A2.25 2.25 0 0 1 1.5 3.25Zm5.677-.177L9.573.677A.25.25 0 0 1 10 .854V2.5h1A2.5 2.5 0 0 1 13.5 5v5.628a2.251 2.251 0 1 1-1.5 0V5a1 1 0 0 0-1-1h-1v1.646a.25.25 0 0 1-.427.177L7.177 3.427a.25.25 0 0 1 0-.354ZM3.75 2.5a.75.75 0 1 0 0 1.5.75.75 0 0 0 0-1.5Zm0 9.5a.75.75 0 1 0 0 1.5.75.75 0 0 0 0-1.5Zm8.25.75a.75.75 0 1 0 1.5 0 .75.75 0 0 0 0-1.5Z"/>',
  merge:'<path d="M5.45 5.154A4.25 4.25 0 0 0 9.25 7.5h1.378a2.251 2.251 0 1 1 0 1.5H9.25A5.734 5.734 0 0 1 5 7.123v3.505a2.25 2.25 0 1 1-1.5 0V5.372a2.25 2.25 0 1 1 1.95-.218ZM4.25 13.5a.75.75 0 1 0 0-1.5.75.75 0 0 0 0 1.5Zm8.5-4.5a.75.75 0 1 0 0-1.5.75.75 0 0 0 0 1.5ZM5 3.25a.75.75 0 1 0 0 .005V3.25Z"/>',
  repo:'<path d="M2 2.5A2.5 2.5 0 0 1 4.5 0h8.75a.75.75 0 0 1 .75.75v12.5a.75.75 0 0 1-.75.75h-2.5a.75.75 0 0 1 0-1.5h1.75v-2h-8a1 1 0 0 0-.714 1.7.75.75 0 1 1-1.072 1.05A2.495 2.495 0 0 1 2 11.5Zm10.5-1h-8a1 1 0 0 0-1 1v6.708A2.486 2.486 0 0 1 4.5 9h8ZM5 12.25a.25.25 0 0 1 .25-.25h3.5a.25.25 0 0 1 .25.25v3.25a.25.25 0 0 1-.4.2l-1.45-1.087a.249.249 0 0 0-.3 0L5.4 15.7a.25.25 0 0 1-.4-.2Z"/>',
  book:'<path d="M0 1.75A.75.75 0 0 1 .75 1h4.253c1.227 0 2.317.59 3 1.501A3.743 3.743 0 0 1 11.006 1h4.245a.75.75 0 0 1 .75.75v10.5a.75.75 0 0 1-.75.75h-4.507a2.25 2.25 0 0 0-1.591.659l-.622.621a.75.75 0 0 1-1.06 0l-.622-.621A2.25 2.25 0 0 0 5.258 13H.75a.75.75 0 0 1-.75-.75Zm7.251 10.324.004-5.073-.002-2.253A2.25 2.25 0 0 0 5.003 2.5H1.5v9h3.757a3.75 3.75 0 0 1 1.994.574ZM8.755 4.75l-.004 7.322a3.752 3.752 0 0 1 1.992-.572H14.5v-9h-3.495a2.25 2.25 0 0 0-2.25 2.25Z"/>',
};

const storedLocale=localStorage.getItem('skillhone.locale');
const requestedLocale=new URLSearchParams(location.search).get('lang');
const initialLocale=requestedLocale==='en'||requestedLocale==='zh'
  ?requestedLocale
  :storedLocale||((navigator.language||'').toLowerCase().startsWith('zh')?'zh':'en');
const state={view:'status',items:{skills:[],issues:[],prs:[],wiki:[],runs:[]},harness:{state:'unavailable',active_runs:0,launch_mode:'unavailable'},audit:{integrity:'failed'},automation:{default:{mode:'queued',interval_minutes:60}},mergePolicy:{mode:'review',scope:'default'},notifications:{approval_required:0},skillId:null,query:'',locale:initialLocale,detail:null,detailType:null,prTab:'conversation',lastUpdated:null};
const $=id=>document.getElementById(id);
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const inlineMarkdown=value=>esc(value)
  .replace(/`([^`]+)`/g,'<code>$1</code>')
  .replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>')
  .replace(/\*([^*]+)\*/g,'<em>$1</em>')
  .replace(/\[([^\]]+)\]\((https?:\/\/[^\s)]+|#[^\s)]+)\)/g,'<a href="$2" target="_blank" rel="noreferrer">$1</a>');
function renderMarkdown(value){
  const lines=String(value??'').replace(/\r/g,'').split('\n');let html='',paragraph=[],list=null,inCode=false,code=[];
  if(lines[0]?.trim()==='---'){
    const end=lines.slice(1).findIndex(line=>line.trim()==='---');
    if(end>=0){const fields=lines.slice(1,end+1).map(line=>line.match(/^([^:]+):\s*(.*)$/)).filter(Boolean);if(fields.length)html+=`<dl class="frontmatter">${fields.map(field=>`<div><dt>${esc(field[1].trim())}</dt><dd>${inlineMarkdown(field[2].trim())}</dd></div>`).join('')}</dl>`;lines.splice(0,end+2)}
  }
  const flushParagraph=()=>{if(paragraph.length){html+=`<p>${paragraph.map(inlineMarkdown).join('<br>')}</p>`;paragraph=[]}};
  const flushList=()=>{if(list){html+=`<${list.type}>${list.items.map(item=>`<li>${inlineMarkdown(item)}</li>`).join('')}</${list.type}>`;list=null}};
  const flushCode=()=>{html+=`<pre><code>${esc(code.join('\n'))}</code></pre>`;code=[]};
  for(const line of lines){
    if(line.startsWith('```')){if(inCode){flushCode();inCode=false}else{flushParagraph();flushList();inCode=true}continue}
    if(inCode){code.push(line);continue}
    if(!line.trim()){flushParagraph();flushList();continue}
    const heading=line.match(/^(#{1,6})\s+(.+)$/);if(heading){flushParagraph();flushList();const level=heading[1].length;html+=`<h${level}>${inlineMarkdown(heading[2])}</h${level}>`;continue}
    const bullet=line.match(/^\s*[-*+]\s+(.+)$/);const ordered=line.match(/^\s*\d+[.)]\s+(.+)$/);
    if(bullet||ordered){flushParagraph();const type=ordered?'ol':'ul';if(list&&list.type!==type)flushList();if(!list)list={type,items:[]};list.items.push((ordered||bullet)[1]);continue}
    const quote=line.match(/^>\s?(.*)$/);if(quote){flushParagraph();flushList();html+=`<blockquote>${inlineMarkdown(quote[1])}</blockquote>`;continue}
    paragraph.push(line)
  }
  if(inCode)flushCode();flushParagraph();flushList();return html
}
const t=(key,values={})=>Object.entries(values).reduce((text,[name,value])=>text.replaceAll(`{${name}}`,String(value)),messages[state.locale][key]??key);
const svg=(name,className='')=>`<svg class="icon ${className}" aria-hidden="true" viewBox="0 0 16 16">${iconPaths[name]}</svg>`;
const nice=value=>value?new Date(value).toLocaleString(state.locale==='zh'?'zh-CN':'en-US',{dateStyle:'medium',timeStyle:'short'}):t('notFinished');
const currentSkill=()=>state.items.skills.find(item=>item.id===state.skillId)||null;
const sourceName=value=>t({existing:'sourceExisting',path:'sourcePath',codex:'sourceCodex',cursor:'Cursor','claude-code':'sourceClaude'}[value]||value);
const prTitle=item=>item.issue_number?item.title.replace(new RegExp(`^Fix #${item.issue_number}:\\s*`),''):item.title;
const currentPolicy=()=>currentSkill()?.automation||state.automation.default;
const currentMergePolicy=()=>currentSkill()?.merge_policy||state.mergePolicy;
const stageLabel=stage=>t(stage||'queued');
const policyLabel=policy=>policy.mode==='scheduled'?`${t('scheduled')} · ${t('everyMinutes',{count:policy.interval_minutes})}`:t(policy.mode||'queued');
const stageBadge=stage=>`<span class="stage-badge ${esc(stage||'queued')}">${esc(stageLabel(stage))}</span>`;

async function api(path,options){const response=await fetch(path,options);if(!response.ok)throw new Error((await response.json()).error||response.statusText);return response.json()}
function filtered(){let items=state.items[state.view];if(state.view!=='skills'&&state.skillId)items=items.filter(item=>item.skill.id===state.skillId);const q=state.query.toLowerCase();return items.filter(item=>`${item.name||''} ${item.title||''} ${item.skill?.name||''} ${item.head||''} ${item.body||''} ${item.slug||''}`.toLowerCase().includes(q))}
function statusText(status){return t(Object.hasOwn(messages.en,status)?status:'open')}
function issueIcon(status){return svg(status==='closed'?'issueClosed':'issue',status==='closed'?'issue-closed':'issue-open')}
function prIcon(status){return svg(status==='merged'?'merge':'pr',status==='merged'?'pr-merged':status==='closed'?'pr-closed':'pr-open')}
function statusPill(status,type){const icon=type==='issue'?issueIcon(status):type==='pr'?prIcon(status):svg(status==='completed'?'issueClosed':'issue');return `<span class="status ${esc(status)}">${icon}${esc(statusText(status))}</span>`}
function countItem(iconName,value,label,className=''){return `<span>${svg(iconName,className)}<strong>${value}</strong> ${esc(label)}</span>`}
function itemHtml(item){
  if(state.view==='skills')return `<button class="item repo-row" data-id="${esc(item.id)}"><div class="item-main"><h3>${svg('repo')}<span>${esc(item.name)}</span></h3><p>${esc(t('imported',{source:sourceName(item.source),branch:item.default_branch}))}</p><div class="count-line">${countItem('issue',item.issue_count,t('issuesShort'),'issue-open')}${countItem('pr',item.pr_count,t('prsShort'),'pr-open')}${countItem('book',item.wiki_count,t('wikiShort'))}${countItem('issueClosed',item.completed_run_count,t('runsShort'),'issue-closed')}</div></div><span class="row-arrow">›</span></button>`;
  if(state.view==='wiki')return `<button class="item" data-id="${esc(item.skill.id)}" data-slug="${esc(item.slug)}"><span class="list-icon">${svg('book')}</span><div class="item-main"><h3>${esc(item.title)}</h3><p>${state.skillId?'':`${esc(item.skill.name)} · `}${esc(t('updatedAt',{time:nice(item.updated_at)}))}</p></div></button>`;
  const type=state.view==='issues'?'issue':'pr';
  const icon=type==='issue'?issueIcon(item.status):prIcon(item.status);
  const meta=type==='issue'?t('updatedAt',{time:nice(item.updated_at)}):`${esc(item.head)} → ${esc(item.base)}`;
  return `<button class="item" data-id="${esc(item.skill.id)}" data-number="${item.number}"><span class="list-icon">${icon}</span><div class="item-main"><h3>${esc(type==='pr'?prTitle(item):item.title)} <span class="muted-number">#${item.number}</span></h3><p>${state.skillId?'':`${esc(item.skill.name)} · `}${meta}</p></div>${type==='issue'?stageBadge(item.stage):item.decision_state==='awaiting_approval'?`<span class="stage-badge review">${esc(t('awaitingApproval'))}</span>`:''}</button>`;
}
function listSummary(items){if(state.view==='skills'||state.view==='wiki')return '';const open=items.filter(item=>item.status==='open').length;const closed=items.filter(item=>item.status==='closed').length;const merged=state.view==='prs'?items.filter(item=>item.status==='merged').length:0;return `<div class="state-summary"><span>${state.view==='issues'?issueIcon('open'):prIcon('open')}${esc(t('openCount',{count:open}))}</span><span>${state.view==='issues'?issueIcon('closed'):prIcon('closed')}${esc(t('closedCount',{count:closed}))}</span>${state.view==='prs'?`<span>${prIcon('merged')}${esc(t('mergedCount',{count:merged}))}</span>`:''}</div>`}
function listPage(){const items=filtered();const label=t({skills:'listSkills',issues:'listIssues',prs:'listPrs',wiki:'listWiki'}[state.view]);return `<div class="page-title"><div><h1>${esc(label)}</h1><p>${esc(t('updated',{time:state.lastUpdated?.toLocaleTimeString(state.locale==='zh'?'zh-CN':'en-US',{hour:'2-digit',minute:'2-digit'})||''}))}</p></div></div><section class="list-panel"><div class="list-toolbar">${listSummary(items)}<label class="search"><span>⌕</span><input id="search" type="search" value="${esc(state.query)}" placeholder="${esc(t('searchPlaceholder',{view:label}))}"></label></div><div class="item-list">${items.length?items.map(itemHtml).join(''):`<div class="list-empty">${esc(t('nothingHere'))}</div>`}</div></section>`}
function runTimeline(runs){if(!runs?.length)return `<p class="body-copy">${esc(t('noRuns'))}</p>`;return `<div class="timeline">${runs.map(run=>`<div class="timeline-row"><div class="timeline-head"><strong>${esc(run.runner)}</strong>${statusPill(run.status,'run')}</div><p>${esc(run.id)} · ${nice(run.started_at)} → ${nice(run.finished_at)}</p><p>${esc(t('branch',{branch:run.branch}))}</p></div>`).join('')}</div>`}
function scopedItems(view){return state.skillId?state.items[view].filter(item=>item.skill?.id===state.skillId):state.items[view]}
function duration(run){if(!run.finished_at)return '—';const seconds=Math.max(0,Math.round((new Date(run.finished_at)-new Date(run.started_at))/1000));return t('seconds',{count:seconds})}
function daySeries(runs){const days=[];for(let offset=6;offset>=0;offset-=1){const date=new Date();date.setHours(0,0,0,0);date.setDate(date.getDate()-offset);const next=new Date(date);next.setDate(next.getDate()+1);days.push({date,count:runs.filter(run=>{const value=new Date(run.started_at);return value>=date&&value<next}).length})}return days}
function approvalInbox(items){return `<section class="status-panel approval-inbox"><header><div><h2>${esc(t('approvalInbox'))}</h2><p>${esc(t('decisionRequired'))}</p></div><span class="stage-badge review">${items.length}</span></header><div>${items.length?items.map(pr=>`<button class="approval-row" data-approval-skill="${esc(pr.skill.id)}" data-approval-number="${pr.number}">${prIcon('open')}<span><strong>${esc(pr.skill.name)} · #${pr.number} ${esc(prTitle(pr))}</strong><small>${esc(pr.head)} → ${esc(pr.base)}</small></span><em>${esc(t('reviewAndMerge'))} →</em></button>`).join(''):`<div class="list-empty">${esc(t('noApprovals'))}</div>`}</div></section>`}
function statusPage(){
  const issues=scopedItems('issues'),prs=scopedItems('prs'),runs=scopedItems('runs');
  const openIssues=issues.filter(item=>item.status==='open').length;
  const awaiting=prs.filter(item=>item.decision_state==='awaiting_approval');
  const counts={queued:0,optimizing:0,review:0,done:0,failed:0};issues.forEach(item=>{counts[item.stage||'queued']=(counts[item.stage||'queued']||0)+1});
  const harness=state.harness,policy=currentPolicy(),merge=currentMergePolicy();
  const harnessLabel=harness.state==='running'?t('running'):harness.state==='idle'?t('idle'):t('unavailable');
  const harnessDetail=harness.installed?t('managedHarness',{version:harness.version||'unknown'}):harness.launch_mode==='on-demand'?t('latestOnDemand'):t('runnerUnavailable');
  const modelState=t(harness.model_configured?'modelReady':'modelMissing');
  const auditState=t(state.audit.integrity==='verified'?'auditVerified':'auditFailed');
  const recent=runs.slice(0,6);
  return `<div class="page-title status-title"><div><h1>${esc(t('status'))}</h1><p>${esc(t('updated',{time:state.lastUpdated?.toLocaleTimeString(state.locale==='zh'?'zh-CN':'en-US',{hour:'2-digit',minute:'2-digit'})||''}))}</p></div></div><section class="status-cards"><button data-status-view="issues">${issueIcon('open')}<span><strong>${openIssues}</strong><small>${esc(t('openIssues'))}</small></span></button><button class="approval-card" data-status-view="prs">${prIcon('open')}<span><strong>${awaiting.length}</strong><small>${esc(t('awaitingApproval'))}</small><em>${esc(t('decisionRequired'))}</em></span></button><article class="harness-card ${esc(harness.state)}"><span class="live-dot"></span><div><strong>${esc(harnessLabel)}</strong><small>${esc(t('harnessStatus'))}</small><em>${esc(harnessDetail)} · ${esc(modelState)} · ${esc(auditState)}</em></div></article><article class="policy-card"><span class="policy-mark">↻</span><div><strong>${esc(policyLabel(policy))}</strong><small>${esc(t('triggerPolicy'))}</small><em>${esc(t('policyCommand',{trigger:policyLabel(policy),merge:t(merge.mode==='automatic'?'mergeAutomatic':'mergeReview')}))}</em></div></article></section><section class="pipeline-panel"><header><h2>${esc(t('pipeline'))}</h2></header><div class="pipeline"><div><strong>${counts.queued}</strong><span>${esc(t('queued'))}</span></div><i>→</i><div><strong>${counts.optimizing}</strong><span>${esc(t('optimizing'))}</span></div><i>→</i><div><strong>${counts.review}</strong><span>${esc(t('review'))}</span></div><i>→</i><div><strong>${counts.done}</strong><span>${esc(t('done'))}</span></div></div></section>${approvalInbox(awaiting)}<section class="status-panel recent-runs"><header><div><h2>${esc(t('recentRuns'))}</h2><p>${esc(t('pipeline'))}</p></div></header><div class="run-list">${recent.length?recent.map(run=>`<button class="run-row" data-run-skill="${esc(run.skill.id)}" data-run-issue="${run.issue_number}"><span class="run-state ${esc(run.status)}">${run.status==='completed'?issueIcon('closed'):issueIcon('open')}</span><div><strong>${esc(run.skill.name)} · Issue #${run.issue_number}</strong><small>${esc(run.runner)} · ${nice(run.started_at)}</small></div><dl><div><dt>${esc(t('duration'))}</dt><dd>${esc(duration(run))}</dd></div><div><dt>${esc(t('toolCalls'))}</dt><dd>${run.tool_call_count??'—'} <small>${run.tool_call_count==null?esc(t('notRecorded')):''}</small></dd></div></dl></button>`).join(''):`<div class="list-empty">${esc(t('noRecentRuns'))}</div>`}</div></section>`
}
function metrics(item){return `<div class="repo-metrics"><button data-view-link="issues">${issueIcon('open')}<strong>${item.issue_count}</strong><span>${esc(t('issues'))}</span></button><button data-view-link="prs">${prIcon('open')}<strong>${item.pr_count}</strong><span>${esc(t('pullRequests'))}</span></button><button data-view-link="wiki">${svg('book')}<strong>${item.wiki_count}</strong><span>${esc(t('wiki'))}</span></button><span>${svg('issueClosed','issue-closed')}<strong>${item.completed_run_count}</strong><small>${esc(t('repairs'))}</small></span></div>`}
function backButton(){return `<button class="back-link" data-action="back">← ${esc(t('backTo',{view:t({skills:'repositories',issues:'issues',prs:'pullRequests',wiki:'wiki'}[state.view])}))}</button>`}
function skillDetail(item){const document=item.document;const body=document?.truncated?`<p>${esc(t('documentTooLarge'))}</p>`:document?renderMarkdown(document.content):`<p>${esc(t('noRepositoryDocument'))}</p>`;return `${backButton()}<section class="repo-overview"><div class="repo-box-head">${svg('repo')}<strong>${esc(item.name)}</strong><span>${esc(item.default_branch)}</span></div>${metrics(item)}<div class="readme-box"><div class="readme-head">${svg('book')}<strong>${esc(document?.name||'README.md')}</strong></div><section class="markdown-body">${body}</section></div></section>`}
function evaluationGateSection(gates){if(!gates?.length)return '';return `<section class="detail-section"><h2>${esc(t('evaluationGates'))}</h2><div class="evaluation-gates">${gates.map(gate=>`<div class="evaluation-gate"><span class="run-state ${esc(gate.status)}">${gate.status==='passing'?issueIcon('closed'):issueIcon('open')}</span><div><strong>${esc(gate.split)}</strong><small>${esc(t('baseline'))}: ${gate.baseline_score} (${gate.baseline_passed}/${gate.baseline_total}) → ${esc(t('candidate'))}: ${gate.candidate_score??esc(t('notEvaluated'))}${gate.candidate_score==null?'':` (${gate.candidate_passed}/${gate.candidate_total})`}</small></div><em>${esc(t(gate.status))}</em></div>`).join('')}</div></section>`}
function issueDetail(item){const hasGates=Boolean(item.evaluation_gates?.length);const tests=item.tests?.length?item.tests.map(test=>`<div class="linked-record issue-test"><span class="run-state ${esc(test.status)}">${test.status==='passing'?issueIcon('closed'):issueIcon('open')}</span><span><strong>${esc(test.path)}</strong><small><code>${esc(test.command)}</code></small></span><em>${esc(t(test.status))}</em></div>`).join(''):`<p class="body-copy">${esc(t('noTests'))}</p>`;const testSection=item.tests?.length||!hasGates?`<section class="detail-section"><h2>${esc(t('reproductionTests'))}</h2>${tests}</section>`:'';return `${backButton()}<header class="record-title"><h1>${esc(item.title)} <span>#${item.number}</span></h1><div class="record-state">${statusPill(item.status,'issue')}${stageBadge(item.stage)}<p>${esc(t('opened',{date:nice(item.created_at)}))}</p></div></header><div class="conversation"><aside>${svg('issue',item.status==='closed'?'issue-closed':'issue-open')}</aside><article class="comment"><header><strong>${esc(t('evidence'))}</strong><span>${esc(nice(item.created_at))}</span></header><div><p class="body-copy">${esc(item.body)||esc(t('noDescription'))}</p></div></article></div>${testSection}${evaluationGateSection(item.evaluation_gates)}<section class="detail-section"><h2>${esc(t('trajectory'))}</h2>${runTimeline(item.runs)}</section><section class="detail-section"><h2>${esc(t('linkedPrs'))}</h2>${item.pull_requests.length?item.pull_requests.map(pr=>`<button class="linked-record" data-go-pr="${pr.number}">${prIcon(pr.status)}<span><strong>#${pr.number} ${esc(prTitle(pr))}</strong><small>${esc(pr.head)} → ${esc(pr.base)}</small></span><em>${esc(statusText(pr.status))}</em></button>`).join(''):`<p class="body-copy">${esc(t('noPr'))}</p>`}</section>`}
function approvalPanel(item){
  if(item.decision_state==='merged'||item.status==='merged')return `<section class="approval-panel merged">${prIcon('merged')}<div><strong>${esc(t('mergedWithApproval'))}</strong><p>${esc(t('localOnly'))}</p></div></section>`;
  return `<section class="approval-panel">${prIcon('open')}<div><strong>${esc(t('mergeApproval'))}</strong><p>${esc(t('mergeApprovalBody'))}</p><small>${esc(t('localOnly'))}</small></div><button class="merge-button" type="button" data-merge-pr>${esc(t('reviewAndMerge'))}</button></section>`
}
function syncPanel(sync){if(!sync)return '';if(sync.state==='takeover_active')return `<section class="approval-panel merged">${issueIcon('closed')}<div><strong>${esc(t('takeoverComplete'))}</strong><p>${esc(t('takeoverCompleteBody'))}</p></div></section>`;if(sync.state==='in_sync')return `<section class="approval-panel merged">${issueIcon('closed')}<div><strong>${esc(t('syncComplete'))}</strong><p>${esc(t('syncCompleteBody'))}</p></div></section>`;if(sync.state==='ready_to_sync')return `<section class="approval-panel">${svg('repo')}<div><strong>${esc(t('syncRequired'))}</strong><p>${esc(t('syncRequiredBody'))}</p></div><button class="merge-button" type="button" data-sync-skill>${esc(t('syncNow'))}</button></section>`;return `<section class="approval-panel">${svg('repo')}<div><strong>${esc(t('syncBlocked'))}</strong><p>${esc(t('syncBlockedBody'))}</p></div></section>`}
function diffLines(patch){if(!patch)return `<div class="diff-empty">${esc(t('noDiff'))}</div>`;return String(patch).split('\n').map(line=>{const kind=line.startsWith('@@')?'hunk':line.startsWith('+')&&!line.startsWith('+++')?'addition':line.startsWith('-')&&!line.startsWith('---')?'deletion':/^(diff --git|index |--- |\+\+\+ )/.test(line)?'meta':'context';const content=['addition','deletion','context'].includes(kind)?line.slice(1):line;return `<div class="diff-line ${kind}"><span>${kind==='addition'?'+':kind==='deletion'?'−':' '}</span><code>${esc(content)||' '}</code></div>`}).join('')}
function prDetail(item){const tabs=['conversation','commits','checks','files'];const selected=tabs.includes(state.prTab)?state.prTab:'conversation';const files=item.files?.map(file=>`<article class="file-diff"><header><b>${esc(file.status)}</b><strong>${esc(file.path)}</strong></header><div class="diff-code">${diffLines(file.patch)}</div>${file.patch_truncated?`<p class="diff-warning">${esc(t('documentTooLarge'))}</p>`:''}</article>`).join('')||`<p class="body-copy">${esc(t('noFiles'))}</p>`;const commits=item.commits?.map(commit=>`<div class="commit"><strong>${esc(commit.subject)}</strong><span>${esc(commit.short_sha)} · ${nice(commit.authored_at)}</span></div>`).join('')||`<p class="body-copy">${esc(t('noCommits'))}</p>`;const description=item.body?renderMarkdown(item.body):`<p>${esc(t('noPrDescription'))}</p>`;const tab=(id,label,count=null,icon='')=>`<button type="button" role="tab" data-pr-tab="${id}" aria-selected="${selected===id}" aria-controls="pr-panel-${id}" class="${selected===id?'active':''}">${icon}${esc(label)}${count===null?'':` <b>${count}</b>`}</button>`;const panel=(id,content)=>`<div id="pr-panel-${id}" class="pr-tab-panel" role="tabpanel" data-pr-panel="${id}"${selected===id?'':' hidden'}>${content}</div>`;const conversation=panel('conversation',`<section class="detail-section pr-description"><h2>${esc(t('prDescription'))}</h2><article class="markdown-body">${description}</article></section>${item.issue?`<section class="detail-section"><h2>${esc(t('closesIssue'))}</h2><button class="linked-record" data-go-issue="${item.issue.number}">${issueIcon(item.issue.status)}<span><strong>#${item.issue.number} ${esc(item.issue.title)}</strong></span><em>${esc(statusText(item.issue.status))}</em></button></section>`:''}`);const commitPanel=panel('commits',`<section class="detail-section"><h2>${esc(t('commits'))}</h2>${commits}</section>`);const checks=panel('checks',`<section class="detail-section"><h2>${esc(t('trajectory'))}</h2>${runTimeline(item.runs)}</section>`);const changed=panel('files',`<section class="detail-section"><h2>${esc(t('changedFiles'))}</h2><p class="diff-stat">${esc(item.diff_stat)||esc(t('noDiff'))}</p><div class="file-diffs">${files}</div></section>`);return `${backButton()}<header class="record-title"><h1>${esc(prTitle(item))} <span>#${item.number}</span></h1><div class="record-state">${statusPill(item.status,'pr')}<p>${esc(t('opened',{date:nice(item.created_at)}))} · ${esc(item.head)} → ${esc(item.base)}</p></div></header>${approvalPanel(item)}${item.status==='merged'?syncPanel(item.sync):''}<nav class="pr-subnav" role="tablist" aria-label="${esc(t('pullRequests'))}">${tab('conversation',t('conversation'),null,svg('issue'))}${tab('commits',t('commits'),item.commits?.length||0)}${tab('checks',t('checks'),item.runs?.length||0)}${tab('files',t('filesChanged'),item.files?.length||0)}</nav>${conversation}${commitPanel}${checks}${changed}`}
function wikiDetail(item){const links=[item.issue_number?`${t('issue')} #${item.issue_number}`:'',item.pr_number?`${t('pr')} #${item.pr_number}`:''].filter(Boolean).join(' · ');return `${backButton()}<header class="record-title wiki-title"><h1>${svg('book')}${esc(item.title)}</h1><div class="record-state"><p>${esc(t('updatedAt',{time:nice(item.updated_at)}))}${links?` · ${esc(links)}`:''}</p></div></header><article class="wiki-document"><header>${svg('book')}<strong>${esc(item.slug)}</strong></header><div><h2>${esc(t('workRecord'))}</h2><p class="wiki-body">${esc(item.body)||esc(t('noNotes'))}</p><h2>${esc(t('agentCommand'))}</h2><pre>skillhone --skill ${esc(item.skill.name)} wiki view ${esc(item.slug)}</pre></div></article>`}
function detailPage(){return state.detailType==='skills'?skillDetail(state.detail):state.detailType==='issues'?issueDetail(state.detail):state.detailType==='prs'?prDetail(state.detail):wikiDetail(state.detail)}
function renderContent(){const content=$('content');content.innerHTML=state.view==='status'?statusPage():state.detail?detailPage():listPage();wireContent()}
function wireContent(){const search=$('search');if(search)search.addEventListener('input',event=>{state.query=event.target.value;renderContent()});document.querySelectorAll('.item').forEach(button=>button.addEventListener('click',()=>state.view==='skills'?openRepo(button.dataset.id):openRecord(button.dataset.id,button.dataset.slug??Number(button.dataset.number))));const back=document.querySelector('[data-action="back"]');if(back)back.addEventListener('click',()=>{state.detail=null;state.detailType=null;location.hash=state.view==='skills'?'skills':state.skillId?`${state.view}/${encodeURIComponent(state.skillId)}`:state.view;renderContent()});document.querySelectorAll('[data-view-link],[data-status-view]').forEach(button=>button.addEventListener('click',()=>switchView(button.dataset.viewLink||button.dataset.statusView)));document.querySelectorAll('[data-run-skill]').forEach(button=>button.addEventListener('click',()=>openRecord(button.dataset.runSkill,Number(button.dataset.runIssue),'issues')));document.querySelectorAll('[data-approval-skill]').forEach(button=>button.addEventListener('click',()=>openRecord(button.dataset.approvalSkill,Number(button.dataset.approvalNumber),'prs')));document.querySelectorAll('[data-pr-tab]').forEach(button=>button.addEventListener('click',()=>{state.prTab=button.dataset.prTab;renderContent()}));const merge=document.querySelector('[data-merge-pr]');if(merge)merge.addEventListener('click',()=>openMergeDialog(state.detail));const sync=document.querySelector('[data-sync-skill]');if(sync)sync.addEventListener('click',()=>openSyncDialog(state.detail));const goIssue=document.querySelector('[data-go-issue]');if(goIssue)goIssue.addEventListener('click',()=>openRecord(state.skillId,Number(goIssue.dataset.goIssue),'issues'));const goPr=document.querySelector('[data-go-pr]');if(goPr)goPr.addEventListener('click',()=>openRecord(state.skillId,Number(goPr.dataset.goPr),'prs'))}
function updateChrome(){const skill=currentSkill();$('repo-name').textContent=skill?.name||(state.view==='status'?'SkillHone':t('skillRepositories'));$('skills-tab-label').textContent=skill?t('code'):t('repositories');$('project').textContent=t('localRepos',{count:state.items.skills.length});const scoped=view=>skill?state.items[view].filter(item=>item.skill?.id===skill.id):state.items[view];$('skill-count').textContent=state.items.skills.length;$('skill-count').hidden=Boolean(skill);$('issue-count').textContent=scoped('issues').length;$('pr-count').textContent=scoped('prs').length;$('wiki-count').textContent=scoped('wiki').length;const dot=document.querySelector('.status-dot');if(dot)dot.className=`status-dot ${state.harness.state}`;document.querySelectorAll('.tab').forEach(element=>element.classList.toggle('active',element.dataset.view===state.view))}
async function openRepo(skillId){state.skillId=skillId;state.view='skills';state.query='';state.detail=await api(`/api/skills/${encodeURIComponent(skillId)}`);state.detailType='skills';location.hash=`repo/${encodeURIComponent(skillId)}`;updateChrome();renderContent()}
async function openRecord(skillId,reference,forcedView=null){state.skillId=skillId;if(forcedView)state.view=forcedView;if(state.view==='prs')state.prTab='conversation';const segment=state.view==='issues'?'issues':state.view==='prs'?'pull-requests':'wiki';state.detail=await api(`/api/skills/${encodeURIComponent(skillId)}/${segment}/${encodeURIComponent(reference)}`);state.detailType=state.view;location.hash=`${state.view==='issues'?'issue':state.view==='prs'?'pr':'wiki'}/${encodeURIComponent(skillId)}/${encodeURIComponent(reference)}`;updateChrome();renderContent()}
function switchView(view){state.view=view;state.query='';state.detail=null;state.detailType=null;updateChrome();if(view==='skills'&&state.skillId){openRepo(state.skillId);return}location.hash=view==='skills'?'skills':state.skillId?`${view}/${encodeURIComponent(state.skillId)}`:view;renderContent()}
function goHome(){state.skillId=null;state.view='status';state.query='';state.detail=null;state.detailType=null;location.hash='status';updateChrome();renderContent()}
function applyLocale(locale){state.locale=locale;localStorage.setItem('skillhone.locale',locale);document.documentElement.lang=locale==='zh'?'zh-CN':'en';document.querySelectorAll('[data-i18n]').forEach(element=>{element.textContent=t(element.dataset.i18n)});document.querySelectorAll('[data-locale]').forEach(button=>button.classList.toggle('active',button.dataset.locale===locale));updateChrome();renderContent()}
async function load(){const data=await api('/api/dashboard');state.items.skills=data.skills;state.items.issues=data.issues;state.items.prs=data.pull_requests;state.items.wiki=data.wiki??[];state.items.runs=data.runs??[];state.harness=data.harness??state.harness;state.audit=data.audit??state.audit;state.automation=data.automation??state.automation;state.mergePolicy=data.merge_policy??state.mergePolicy;state.notifications=data.notifications??state.notifications;state.lastUpdated=new Date();updateChrome();renderContent()}
let pendingMerge=null;
function openMergeDialog(item){const copyMode=Boolean(item.sync?.origins?.some(origin=>origin.mode==='copy'));pendingMerge={skillId:String(item.skill.id),number:Number(item.number),copyMode};$('merge-pr-name').textContent=`${item.skill.name} · #${item.number} ${prTitle(item)}`;$('merge-dialog-body').textContent=t(copyMode?'mergeAndSyncBody':'confirmMergeBody');$('merge-confirm').textContent=t(copyMode?'mergeAndSync':'mergeLocally');$('merge-error').hidden=true;$('merge-error').textContent='';$('merge-confirm').disabled=false;$('merge-dialog').showModal()}
async function confirmMerge(){if(!pendingMerge)return;const target={...pendingMerge},button=$('merge-confirm');button.disabled=true;$('merge-error').hidden=true;try{const headers={'X-SkillHone-Confirm':'merge'};if(target.copyMode)headers['X-SkillHone-Sync']='apply';await api(`/api/skills/${encodeURIComponent(target.skillId)}/pull-requests/${target.number}/merge`,{method:'POST',headers});$('merge-dialog').close();await load();await openRecord(target.skillId,target.number,'prs')}catch(error){$('merge-error').textContent=error instanceof Error?error.message:t('mergeFailed');$('merge-error').hidden=false;button.disabled=false}}
let pendingSync=null;
function openSyncDialog(item){pendingSync={skillId:String(item.skill.id),number:Number(item.number)};$('sync-skill-name').textContent=item.skill.name;$('sync-error').hidden=true;$('sync-error').textContent='';$('sync-confirm').disabled=false;$('sync-dialog').showModal()}
async function confirmSync(){if(!pendingSync)return;const target={...pendingSync},button=$('sync-confirm');button.disabled=true;$('sync-error').hidden=true;try{await api(`/api/skills/${encodeURIComponent(target.skillId)}/sync`,{method:'POST',headers:{'X-SkillHone-Confirm':'sync'}});$('sync-dialog').close();await load();await openRecord(target.skillId,target.number,'prs')}catch(error){$('sync-error').textContent=error instanceof Error?error.message:t('syncFailed');$('sync-error').hidden=false;button.disabled=false}}
async function restoreHash(){const parts=location.hash.replace(/^#/,'').split('/');if(parts[0]==='repo'&&parts[1])return openRepo(decodeURIComponent(parts[1]));if(['issue','pr','wiki'].includes(parts[0])&&parts[1]&&parts[2]){state.view={issue:'issues',pr:'prs',wiki:'wiki'}[parts[0]];return openRecord(decodeURIComponent(parts[1]),decodeURIComponent(parts[2]))}if(parts[0]==='status'){state.view='status';state.skillId=parts[1]?decodeURIComponent(parts[1]):null;updateChrome();renderContent();return}if(['skills','issues','prs','wiki'].includes(parts[0])){state.view=parts[0];state.skillId=parts[1]?decodeURIComponent(parts[1]):null;updateChrome();renderContent();return}goHome()}

document.querySelectorAll('.icon-slot').forEach(slot=>{slot.innerHTML=svg(slot.dataset.icon)});
document.querySelectorAll('.tab').forEach(tab=>tab.addEventListener('click',()=>switchView(tab.dataset.view)));
document.querySelectorAll('[data-locale]').forEach(button=>button.addEventListener('click',()=>applyLocale(button.dataset.locale)));
$('home-link').addEventListener('click',event=>{event.preventDefault();goHome()});
$('merge-close').addEventListener('click',()=>$('merge-dialog').close());
$('merge-cancel').addEventListener('click',()=>$('merge-dialog').close());
$('merge-confirm').addEventListener('click',confirmMerge);
$('merge-dialog').addEventListener('close',()=>{pendingMerge=null;$('merge-confirm').disabled=false;$('merge-error').hidden=true});
$('sync-close').addEventListener('click',()=>$('sync-dialog').close());
$('sync-cancel').addEventListener('click',()=>$('sync-dialog').close());
$('sync-confirm').addEventListener('click',confirmSync);
$('sync-dialog').addEventListener('close',()=>{pendingSync=null;$('sync-confirm').disabled=false;$('sync-error').hidden=true});
document.querySelectorAll('[data-locale]').forEach(button=>button.classList.toggle('active',button.dataset.locale===state.locale));
document.documentElement.lang=state.locale==='zh'?'zh-CN':'en';
document.querySelectorAll('[data-i18n]').forEach(element=>{element.textContent=t(element.dataset.i18n)});
load().then(restoreHash).catch(error=>{$('content').innerHTML=`<div class="empty"><h2>${esc(error.message)}</h2></div>`});
setInterval(load,5000);
